version: '3.9'

services:
  database:
    container_name: api_mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: api_db
      MYSQL_USER: alexandr
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"